


spring.datasource.url=j
spring.datasource.driverClassName=
spring.datasource.username=sa
spring.datasource.password=password

spring.jpa.database-platform=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console


spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  properties:
    hibernate:
      show-sql: true
      format-sql: true