spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pagTest?useTimeZone=true&serverTimezone=UTC
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: Vyknon@12
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
  properties:
    hibernate:
      show-sql: true
      format-sql: true

